WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /session/72b694c0cbf84340556b6bc4651b6fa8
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d800750>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/72b694c0cbf84340556b6bc4651b6fa8
WARNING  urllib3.connectionpool:connectionpool.py:662 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d800a90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/72b694c0cbf84340556b6bc4651b6fa8