{"uuid": "0bc30b15-b163-4d26-bc8f-4be11a6aeb67", "children": ["f46f528e-26b4-4293-b9c0-d64196aa6725"], "befores": [{"name": "app", "status": "passed", "start": 1565709642614, "stop": 1565709644663}], "afters": [{"name": "app::destroy", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/allure_commons/_allure.py\", line 181, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/artyomlagunkov/demobcd/fixture/application.py\", line 122, in destroy\n    self.wd.quit()\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1565709697419, "stop": 1565709697451}], "start": 1565709642614, "stop": 1565709697455}