{"uuid": "2984183d-6c38-44c3-beb7-8e970b4ab329", "children": ["7bbeae51-9c03-4fdb-8963-23c23f41edf0", "b72a2b30-eb93-45dd-baab-eb0be5504ea3", "9f5f1b75-5cf5-46be-8292-840ffcfe6b5f"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/home/tester/demobcd/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/tester/demobcd/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/tester/demobcd/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 783, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/home/tester/demobcd/conftest.py\", line 35, in app\n    fixture = Application()\n  File \"/home/tester/demobcd/fixture/application.py\", line 18, in __init__\n    self.wd = WebDriver(executable_path='../demobcd/drivers/chromedriver')\n  File \"/home/tester/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/home/tester/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1565585767443, "stop": 1565585767445}], "start": 1565585767443, "stop": 1565585767556}