{"uuid": "43e0de0b-7a10-4faf-b5cb-3fa910c835dd", "children": ["1f6f1c6b-5b11-46f7-bf20-bc8b36a4dda3"], "befores": [{"name": "app", "status": "passed", "start": 1565789436828, "stop": 1565789440625}], "afters": [{"name": "app::destroy", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/allure_commons/_allure.py\", line 181, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/artyomlagunkov/demobcd/fixture/application.py\", line 122, in destroy\n    self.wd.quit()\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1565789503411, "stop": 1565789503429}], "start": 1565789436828, "stop": 1565789503429}