{"uuid": "a5beb3a7-0584-47a7-b111-0ec257e1355f", "children": ["02507fa9-115c-4c78-8d34-cbac4879cfc4"], "befores": [{"name": "app", "status": "passed", "start": 1565622808201, "stop": 1565622810129}], "afters": [{"name": "app::destroy", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/allure_commons/_allure.py\", line 181, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/artyomlagunkov/demobcd/fixture/application.py\", line 114, in destroy\n    self.wd.quit()\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/artyomlagunkov/demobcd/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1565622878806, "stop": 1565622878814}], "start": 1565622808201, "stop": 1565622878814}